package HelloApp;

/**
* HelloApp/OperadoresHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* miércoles 1 de marzo de 2023 14H08' CET
*/

public final class OperadoresHolder implements org.omg.CORBA.portable.Streamable
{
  public HelloApp.Operadores value = null;

  public OperadoresHolder ()
  {
  }

  public OperadoresHolder (HelloApp.Operadores initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.OperadoresHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.OperadoresHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.OperadoresHelper.type ();
  }

}
