package PrathamCalculator;


/**
* PrathamCalculator/CalcOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, February 24, 2023 7:37:16 PM CET
*/

public interface CalcOperations 
{

  //Performs the Calculations:ADD/SUB/MUL/DIV
  int calculate (int _operator, int num1, int num2);

  //The Server EXITS when the Client prompts it to do so
  void shutdown ();
} // interface CalcOperations
