package PrathamCalculator;

/**
* PrathamCalculator/CalcHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, February 24, 2023 7:37:16 PM CET
*/

public final class CalcHolder implements org.omg.CORBA.portable.Streamable
{
  public PrathamCalculator.Calc value = null;

  public CalcHolder ()
  {
  }

  public CalcHolder (PrathamCalculator.Calc initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PrathamCalculator.CalcHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PrathamCalculator.CalcHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PrathamCalculator.CalcHelper.type ();
  }

}
