package PrathamCalculator;


/**
* PrathamCalculator/CalcHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, February 24, 2023 7:37:16 PM CET
*/

abstract public class CalcHelper
{
  private static String  _id = "IDL:PrathamCalculator/Calc:1.0";

  public static void insert (org.omg.CORBA.Any a, PrathamCalculator.Calc that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static PrathamCalculator.Calc extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (PrathamCalculator.CalcHelper.id (), "Calc");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static PrathamCalculator.Calc read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_CalcStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, PrathamCalculator.Calc value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static PrathamCalculator.Calc narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PrathamCalculator.Calc)
      return (PrathamCalculator.Calc)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PrathamCalculator._CalcStub stub = new PrathamCalculator._CalcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static PrathamCalculator.Calc unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof PrathamCalculator.Calc)
      return (PrathamCalculator.Calc)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      PrathamCalculator._CalcStub stub = new PrathamCalculator._CalcStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
