package MCalculadora;

/**
 * MCalculadora/ICalculadoraOperations.java .
 * Generated by the IDL-to-Java compiler (portable), version "3.2"
 * from Calculadora.idl
 * Friday, February 24, 2023 7:40:37 PM CET
 */

public interface ICalculadoraOperations {
  int sumar(MCalculadora.Operadores Ops);

  int restar(MCalculadora.Operadores Ops);

  int multiplicar(MCalculadora.Operadores Ops);

  int dividir(MCalculadora.Operadores Ops);

  int factorial(MCalculadora.Operadores Ops);
} // interface ICalculadoraOperations
