package MCalculadora;


/**
* MCalculadora/ICalculadoraOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Wednesday, March 1, 2023 10:21:44 AM CET
*/

public interface ICalculadoraOperations 
{
  int sumar (MCalculadora.Operadores Ops);
  int restar (MCalculadora.Operadores Ops);
  int multiplicar (MCalculadora.Operadores Ops);
  int dividir (MCalculadora.Operadores Ops);
  int factorial (MCalculadora.Operadores Ops);
} // interface ICalculadoraOperations
