package MCalculadora;


/**
* MCalculadora/ICalculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Friday, February 24, 2023 7:40:37 PM CET
*/

public interface ICalculadora extends ICalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICalculadora
