package MCalculadora;


/**
* MCalculadora/ICalculadora.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Wednesday, March 1, 2023 10:21:44 AM CET
*/

public interface ICalculadora extends ICalculadoraOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICalculadora
