package MCalculadora;


/**
* MCalculadora/Operadores.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Wednesday, March 1, 2023 10:21:44 AM CET
*/

public final class Operadores implements org.omg.CORBA.portable.IDLEntity
{
  public int a = (int)0;
  public int b = (int)0;

  public Operadores ()
  {
  } // ctor

  public Operadores (int _a, int _b)
  {
    a = _a;
    b = _b;
  } // ctor

} // class Operadores
