module HelloApp
{
      typedef long arr[4];
  interface Hello
  {
      string sayHello();
        long suma(in long a, in long b);
        long restar(in long a, in long b);
        long multiplicar(in long a, in long b);
        long dividir(in long a, in long b);
        long factorial(in long a);
        long potencia(in long a, in long b);
        long logaritmo(in long a);
        long raiz(in long a);
        string derivar(in long a, in arr b);
  oneway void shutdown();
  };
};
