/*      Calculadora.idl     */
module MCalculadora {
    struct Operadores {
        long a;
        long b;
    };
    interface ICalculadora
    {
        long sumar(in Operadores Ops);
        long restar(in Operadores Ops);
        long multiplicar(in Operadores Ops);
        long dividir(in Operadores Ops);
    };
};