package Biblioteca;


/**
* Biblioteca/GestionBiblioteca.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Biblioteca.idl
* viernes, 15 de marzo de 2024, 21:05:35 (hora est·ndar de Europa central)
*/


// Define la interfaz para el sistema de gesti√≥n de la biblioteca
public interface GestionBiblioteca extends GestionBibliotecaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GestionBiblioteca
