package HelloApp;


/**
* HelloApp/arrHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* viernes 3 de marzo de 2023 11H12' CET
*/

public final class arrHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public arrHolder ()
  {
  }

  public arrHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = HelloApp.arrHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    HelloApp.arrHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return HelloApp.arrHelper.type ();
  }

}
