package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* viernes 3 de marzo de 2023 11H12' CET
*/

public interface HelloOperations 
{
  String sayHello ();
  int suma (int a, int b);
  int restar (int a, int b);
  int multiplicar (int a, int b);
  int dividir (int a, int b);
  int factorial (int a);
  int potencia (int a, int b);
  int logaritmo (int a);
  int raiz (int a);
  String derivar (int a, int[] b);
  void shutdown ();
} // interface HelloOperations
