package HelloApp;


/**
* HelloApp/HelloPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* viernes 3 de marzo de 2023 11H12' CET
*/

public abstract class HelloPOA extends org.omg.PortableServer.Servant
 implements HelloApp.HelloOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("sayHello", new java.lang.Integer (0));
    _methods.put ("suma", new java.lang.Integer (1));
    _methods.put ("restar", new java.lang.Integer (2));
    _methods.put ("multiplicar", new java.lang.Integer (3));
    _methods.put ("dividir", new java.lang.Integer (4));
    _methods.put ("factorial", new java.lang.Integer (5));
    _methods.put ("potencia", new java.lang.Integer (6));
    _methods.put ("logaritmo", new java.lang.Integer (7));
    _methods.put ("raiz", new java.lang.Integer (8));
    _methods.put ("derivar", new java.lang.Integer (9));
    _methods.put ("shutdown", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // HelloApp/Hello/sayHello
       {
         String $result = null;
         $result = this.sayHello ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // HelloApp/Hello/suma
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.suma (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 2:  // HelloApp/Hello/restar
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.restar (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 3:  // HelloApp/Hello/multiplicar
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.multiplicar (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // HelloApp/Hello/dividir
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.dividir (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 5:  // HelloApp/Hello/factorial
       {
         int a = in.read_long ();
         int $result = (int)0;
         $result = this.factorial (a);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // HelloApp/Hello/potencia
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.potencia (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 7:  // HelloApp/Hello/logaritmo
       {
         int a = in.read_long ();
         int $result = (int)0;
         $result = this.logaritmo (a);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 8:  // HelloApp/Hello/raiz
       {
         int a = in.read_long ();
         int $result = (int)0;
         $result = this.raiz (a);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 9:  // HelloApp/Hello/derivar
       {
         int a = in.read_long ();
         int b[] = HelloApp.arrHelper.read (in);
         String $result = null;
         $result = this.derivar (a, b);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // HelloApp/Hello/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:HelloApp/Hello:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Hello _this() 
  {
    return HelloHelper.narrow(
    super._this_object());
  }

  public Hello _this(org.omg.CORBA.ORB orb) 
  {
    return HelloHelper.narrow(
    super._this_object(orb));
  }


} // class HelloPOA
