package HelloApp;


/**
* HelloApp/Operadores.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./Hello.idl
* miércoles 1 de marzo de 2023 14H08' CET
*/

public final class Operadores implements org.omg.CORBA.portable.IDLEntity
{
  public int d[] = null;

  public Operadores ()
  {
  } // ctor

  public Operadores (int[] _d)
  {
    d = _d;
  } // ctor

} // class Operadores
