//A container which holds all the interfaces,methods,parameters,exceptions,events etc.
module PrathamCalculator

{

interface Calc

{

//Performs the Calculations:ADD/SUB/MUL/DIV
long calculate(in long operator,in long num1,in long num2);

//The Server EXITS when the Client prompts it to do so
oneway void shutdown();                   

};

};